version: '3.3'
services:
  db:
    image: postgres:10
    container_name: postgres10
    ports:
      - "10015:5432"
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data
    restart: always             # run as a service
    volumes:
      - ./postgresql:/var/lib/postgresql/data

#  odoo12:
#    image: odoo:12.0
#    build: .
#    container_name: odoo12
#    depends_on:
#      - db
#    ports:
#      - "10069:8069"
#      - "10072:8072"
#    tty: true
#    command: -- --dev=reload
#    command: odoo scaffold /mnt/extra-addons/test_module
#    environment:
#      - HOST=db
#      - USER=odoo
#      - PASSWORD=odoo
#    volumes:
#      - ./data:/var/lib/odoo
#      - ./addons:/mnt/extra-addons
#      - ./etc:/etc/odoo
#      - odoo12-backup:/customs/backups
#    restart: always             # run as a service
  odoo14:
    image: odoo:14.0
    container_name: odoo14
    depends_on:
      - db
    ports:
      - "10021:8069"
      - "10022:8072"
    tty: true
    command: -- --dev=reload
#    command: odoo scaffold /mnt/extra-addons/test_module
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - odoo14-backup:/customs/backups
    restart: always             # run as a service
volumes:
  odoo12-backup:
  odoo14-backup:
