version: '3.9'
services:
  db:
    image: postgres:10
    container_name: postgres10
    ports:
      - "10015:5432"
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data
    restart: always             # run as a service
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  odoo12:
    image: odoo:12.0
    container_name: odoo12
    depends_on:
      - db
    ports:
      - "10069:8069"
      - "10072:8072"
    tty: true
    command: -- --dev=reload
#    command: odoo scaffold /mnt/extra-addons/test_module
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service

